### ISSUE TITLE
As a system admin user I should be able to create fleet Owners

### ISSUE THREAD

**Issue by hossein-85** [hossein-85/Rabit#3]
**Tasks**
- [ ] Create the Endpoint
- [ ] Create the required model layer methods in order to create an owner
- [ ] Perform the required ACL checks
- [ ] As part of this ticket create the required Abstract Entity, Model, DAO and ACL check classes
- [ ] The owner entity will have the following properties for now:

`
id
name,
date_created
date_updated
 `
