### ISSUE TITLE
As an owner I should be able to create fleet Schedulers

### ISSUE THREAD

**Issue by hossein-85** [hossein-85/Rabit#4]
**Tasks**
- [ ] Create the Endpoint
- [ ] Create the required model layer methods in order to create a Scheduler
- [ ] Perform the required ACL checks: `SysAdmin`, `Owner`
- [ ] The Scheduler entity will have the following properties for now:

`
id,
name,
owner_id
date_created
date_updated
 `
