### ISSUE TITLE
As a system admin user I should be able to create an Operator

### ISSUE THREAD

**Issue by hossein-85** [hossein-85/Rabit#5]
**Tasks**
- [ ] Create the Endpoint
- [ ] Create the required model layer methods in order to create a Operator
- [ ] Perform the required ACL checks: `SysAdmin`, `Owner`
- [ ] The Operator entity will have the following properties for now:

`
id,
name,
address_id
date_created
date_updated
 `
