### ISSUE TITLE
As a system admin user I should be able to create a SysAdmin

### ISSUE THREAD

**Issue by hossein-85** [hossein-85/Rabit#6]
**Tasks**
- [ ] Create the Endpoint
- [ ] Create the required model layer methods in order to create a SysAdmin
- [ ] Perform the required ACL checks: `SysAdmin`
- [ ] The SysAdmin entity will have the following properties for now:

`
id,
name,
addresses,
emails,
tel_numbers,
date_created
date_updated
 `
