### ISSUE TITLE
As a Scheduler I should be able to create a Reservation

### ISSUE THREAD

**Issue by hossein-85** [hossein-85/Rabit#7]
**Tasks**
- [ ] Create the Endpoint
- [ ] Create the required model layer methods in order to create a Reservation
- [ ] Perform the required ACL checks: `SysAdmin`, `Owner`, `Scheduler`
- [ ] The Reservation entity will have the following properties for now:

`
id,
start_date,
end_date,
robot_id,
operator_id,
operator_name
date_created
date_updated
 `
- [ ] Validate that the Robot is available for the passed in period
